<a href="https://colab.research.google.com/github/tcurtis714/lis4693/blob/main/lab-3/Lab3_data_visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 3: Data Visualization using altair

## Import packages

In [1]:
%pip install -U altair

Requirement already satisfied: altair in /usr/local/lib/python3.12/dist-packages (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair) (4.26.0)
Requirement already satisfied: narwhals>=1.27.1 in /usr/local/lib/python3.12/dist-packages (from altair) (2.17.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair) (26.0)
Requirement already satisfied: typing-extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from altair) (4.15.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (0.30.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair) (3.0.3)

In [2]:
import pandas as pd
import altair as alt
from vega_datasets import data as vega_data
import requests
import io

## Load 'Seattle Library Data' and save as data frame

In [3]:
url = "https://raw.githubusercontent.com/manika-lamba/SP26-LIS4_5693/refs/heads/main/lab-assignments/lab-3/Seattle-Library_2015-2021.csv"
response = requests.get(url)
response.raise_for_status() # Raise an exception for HTTP errors
text = response.text

In [4]:
# Save data as dataframe
seattle_df = pd.read_csv(io.StringIO(text))
seattle_df.head()

,Title,Creator,MaterialType,Checkouts,CheckoutYear,CheckoutMonth,Publisher,PublicationYear,Subjects,UsageClass,CheckoutType
0,Frog and toad all year / by Arnold Lobel.,"Lobel, Arnold",BOOK,34,2016,10,"Harper & Row,",c1976.,"Friendship Fiction, Frogs Juvenile fiction, To...",Physical,Horizon
1,"My brilliant friend : childhood, adolescence /...","Ferrante, Elena",BOOK,110,2016,10,"Europa Editions,",2012,"Friendship Fiction, Naples Italy Fiction",Physical,Horizon
2,Star trek [videorecording] / Paramount ; Spygl...,NaN,VIDEODISC,36,2016,10,"Paramount Home Entertainment,",c2009.,"Kirk James T 2233 2371 Drama, Spock Mr Drama, ...",Physical,Horizon
3,The Man in the High Castle,Philip K. Dick,EBOOK,63,2016,10,Houghton Mifflin Harcourt Trade and Reference,2012,"Fiction, Science Fiction",Digital,OverDrive
4,"The Fifth Season: Broken Earth Series, Book 1",N. K. Jemisin,EBOOK,44,2016,10,"Hachette Digital, Inc.",2015,"Fantasy, Fiction, Thriller",Digital,OverDrive

## TASK 1: Visualize two columns from data frame

In [9]:
seattle_df['UsageClass'].value_counts()

UsageClass
Physical    184181
Digital      98106
Name: count, dtype: int64

In [10]:
seattle_df['CheckoutType'].value_counts()

CheckoutType
Horizon      184181
OverDrive     91841
Zinio          4197
Hoopla         1093
Freegal         975
Name: count, dtype: int64

### Create data frames for the 'UsageClass' and 'CheckoutType' columns

In [6]:
source1 = seattle_df['UsageClass'].value_counts().rename_axis('UsageClass').reset_index(name='counts')

In [11]:
source2 = seattle_df['CheckoutType'].value_counts().rename_axis('CheckoutType').reset_index(name='counts')

### Create pie chart for the 'UsageClass' column

In [7]:
alt.Chart(source1).mark_arc().encode(
    theta="counts",
    color="UsageClass"
)

alt.Chart(...)

### Create horizontal bar chart for the 'CheckoutType' column

In [27]:
alt.Chart(source2).mark_bar().encode(
    x="counts",
    y="CheckoutType"
)

alt.Chart(...)

## TASK 3: Add interactivity

### Adding a click function to the legend the change opacity in the chart

In [35]:
selection = alt.selection_point(fields=['UsageClass'], bind='legend')
alt.Chart(source1).mark_arc().encode(
    theta="counts",
    color="UsageClass",
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2))
).add_params(
    selection
)

alt.Chart(...)

### Add a hover function the chart that shows the exact count number

In [30]:
alt.Chart(source2).mark_bar().encode(
    x="counts",
    y="CheckoutType",
    tooltip='counts'
).interactive()

alt.Chart(...)

## TASK 4: Horizontal Concatenation

In [33]:
base1 = alt.Chart(source1).encode(
    theta="counts",
    color="UsageClass",
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2))
).add_params(
    selection
)
base2 = alt.Chart(source2).encode(
    x="counts",
    y="CheckoutType",
    tooltip='counts'
).interactive()
alt.hconcat(base1.mark_arc(),
            base2.mark_bar())

alt.HConcatChart(...)

## TASK 5: Reflection
One problem I had is that the vizualizations were not showing up in colab. I had update the altair package to the latest version. After that I didn't have any problems. Creating a pie chart and adding interactivity to it went well.